// vue-app/src/components/Footer.vue
<template>
	<footer class="w-full bg-checkerr-green text-gray-400">
		<div class="max-w-[1440px] mx-auto py-6 px-4 sm:px-6 lg:px-8">
			<div class="text-center">
				<p class="text-sm">
					&copy; {{ new Date().getFullYear() }} Chekaa. All rights reserved.
				</p>
			</div>
		</div>
	</footer>
</template>

<script setup>
</script>

// react-app/src/components/Footer.jsx
export default function Footer() {
	return (
		<footer className="w-full bg-green-950 text-gray-400">
			<div className=" mx-auto py-6 px-4 sm:px-6 lg:px-8">
				<div className="text-center">
					<p className="text-sm">
						&copy; {new Date().getFullYear()} Chekaa. All rights reserved.
					</p>
				</div>
			</div>
		</footer>
	);
}
