// vue-app/src/components/Header.vue
<template>
	<header
		class="h-16 bg-white shadow-md flex items-center justify-between px-6 shrink-0">
		<div class="flex items-center">
			<span v-if="user" class="hidden sm:inline mr-3 font-medium text-gray-700">
				Welcome, {{ user.name }}
			</span>

			<div
				class="w-10 h-10 bg-checkerr-orange rounded-full flex items-center justify-center text-white font-bold">
				{{ userInitial }}
			</div>
		</div>

		<button
			@click="logout"
			class="flex items-center gap-1 rounded-sm hover:bg-slate-300/30 px-4 py-2">
			<span>
				<v-icon name="hi-logout" />
			</span>
			Logout
		</button>
	</header>
</template>

<script setup>
import { storeToRefs } from "pinia";
import { useAuthStore } from "@/stores/authStore";

const authStore = useAuthStore();


const { user, userInitial } = storeToRefs(authStore);
const { logout } = authStore;
</script>

// react-app/src/components/Header.jsx
import { HiLogout, HiMenu, HiX } from "react-icons/hi";
import { useAuth } from "../contexts/AuthProvider";

export default function Header() {
	const { logout, user } = useAuth();

	const { name } = user;
	console.log("Hey", name);
	return (
		<header className="h-16 bg-white shadow-md flex items-center justify-between px-6 shrink-0">
			<div className="flex items-center">
				<span className="hidden sm:inline mr-3 font-medium text-gray-700">
					Welcome, {name}
				</span>
				<div className="w-10 h-10 bg-orange-500 rounded-full flex items-center justify-center text-white font-bold">
					U
				</div>
			</div>
			<button
				onClick={logout}
				className="flex items-center gap-1 rounded-sm hover:bg-slate-300/30 px-4 py-2">
				<span>
					<HiLogout />
				</span>
				Logout
			</button>
		</header>
	);
}
