// react-app/src/components/AppLayout.jsx
import { useState } from "react";
import Header from "./Header"; // We will create this
import Sidebar from "./Sidebar"; // We will create this
import AppContainer from "./AppContainer";
import { Outlet } from "react-router-dom";

export default function AppLayout() {
	const [isSidebarOpen, setIsSidebarOpen] = useState(false);

	const toggleSidebar = () => {
		setIsSidebarOpen(!isSidebarOpen);
	};

	return (
		<AppContainer>
			<div className="flex h-screen overflow-hidden bg-gray-100">
				<Sidebar
					onToggleSidebar={toggleSidebar}
					isSidebarOpen={isSidebarOpen}
				/>

				<div className="flex-1 flex flex-col overflow-hidden">
					<Header
						onToggleSidebar={toggleSidebar}
						isSidebarOpen={isSidebarOpen}
					/>

					<main className="flex-1 overflow-auto p-6 md:p-8">
						<div className="block sm:hidden">
							{!isSidebarOpen && <Outlet />}
						</div>
						<div className="sm:block hidden">
							<Outlet />
						</div>
					</main>
				</div>
			</div>
		</AppContainer>
	);
}

// vue-app/src/components/AppLayout.vue
<template>
  <AppContainer>
    <div class="flex h-screen overflow-hidden bg-gray-100">
      
      <Sidebar 
        :is-sidebar-open="isSidebarOpen"
        @toggle-sidebar="toggleSidebar" 
      />
      
      <div class="flex-1 flex flex-col overflow-hidden">
        
        <Header />
        
        <main class="flex-1 overflow-auto p-6 md:p-8">
          <div class="block sm:hidden">
            <RouterView v-if="!isSidebarOpen" />
          </div>
          <div class="sm:block hidden">
            <RouterView />
          </div>
        </main>
      </div>
    </div>
  </AppContainer>
</template>

<script setup>
import { ref } from 'vue'
import { RouterView } from 'vue-router'

import AppContainer from '../components/AppContainer.vue'
import Sidebar from '../components/Sidebar.vue'
import Header from '../components/Header.vue'

const isSidebarOpen = ref(false)

function toggleSidebar() {
  isSidebarOpen.value = !isSidebarOpen.value
}
</script>
