// react-app/src/components/NavLink.jsx
import { Link } from "react-router-dom";

export default function NavLink({
	icon,
	text,
	to,
	isSidebarOpen,
	onToggleSidebar,
}) {
	return (
		<Link
			to={to}
			onClick={isSidebarOpen && onToggleSidebar}
			className={`
        flex items-center p-3 rounded-lg text-gray-300
        hover:bg-green-800 hover:text-white
        ${isSidebarOpen ? "justify-start" : "justify-center"}
      `}>
			{icon}
			<span
				className={`
          ml-4 font-medium transition-opacity
          ${isSidebarOpen ? "opacity-100" : "opacity-0 absolute"}
        `}>
				{text}
			</span>
		</Link>
	);
}

// vue-app/src/components/NavLink.vue
<template>
	<RouterLink
		:to="to"
		@click="handleClick"
		:class="[
			'flex items-center p-3 rounded-lg text-gray-300',
			'hover:bg-green-800 hover:text-white',
			isSidebarOpen ? 'justify-start' : 'justify-center',
		]">
		<slot />

		<span
			:class="[
				'ml-4 font-medium transition-opacity',
				isSidebarOpen ? 'opacity-100' : 'opacity-0 absolute',
			]">
			{{ text }}
		</span>
	</RouterLink>
</template>

<script setup>
import { RouterLink } from "vue-router";

const props = defineProps({
	to: {
		type: String,
		required: true,
	},
	text: {
		type: String,
		required: true,
	},
	isSidebarOpen: {
		type: Boolean,
		default: false,
	},
});

const emit = defineEmits(["toggleSidebar"]);

function handleClick() {
	if (props.isSidebarOpen) {
		emit("toggleSidebar");
	}
}
</script>
