// react-app/src/components/Sidebar.jsx
import { HiMenu, HiOutlineHome, HiOutlineTicket, HiX } from "react-icons/hi";
import NavLink from "./NavLink";

export default function Sidebar({ onToggleSidebar, isSidebarOpen }) {
	return (
		<div
			className={`
shrink-0 bg-green-950 text-white flex flex-col
        transition-all duration-300 ease-in-out
        ${isSidebarOpen ? "w-60" : "w-20"}
      `}>
			<button
				onClick={onToggleSidebar}
				className="text-gray-600 hover:text-orange-500 focus:outline-none m-[1rem_auto] w-fit"
				aria-label="Toggle sidebar ">
				{isSidebarOpen ? <HiX size={28} /> : <HiMenu size={28} />}
			</button>

			<nav className="flex-1 overflow-y-auto p-4 space-y-2">
				<NavLink
					icon={<HiOutlineHome size={24} />}
					text="Dashboard"
					to="/dashboard"
					isSidebarOpen={isSidebarOpen}
					onToggleSidebar={onToggleSidebar}
				/>
				<NavLink
					icon={<HiOutlineTicket size={24} />}
					text="Tickets"
					to="/tickets"
					isSidebarOpen={isSidebarOpen}
					onToggleSidebar={onToggleSidebar}
				/>
			</nav>
		</div>
	);
}

// vue-app/src/components/Sidebar.vue
<template>
	<div
		:class="[
			'flex-shrink-0 bg-checkerr-green text-white flex flex-col',
			'transition-all duration-300 ease-in-out',
			isSidebarOpen ? 'w-60' : 'w-20',
		]">
		<button
			@click="$emit('toggleSidebar')"
			class="text-gray-300 hover:text-checkerr-orange focus:outline-none m-[1rem_auto] w-fit"
			aria-label="Toggle sidebar">
			<v-icon v-if="isSidebarOpen" name="hi-x" scale="1.75" />
			<v-icon v-else name="hi-menu" scale="1.75" />
		</button>

		<nav class="flex-1 overflow-y-auto p-4 space-y-2">
			<NavLink
				to="/dashboard"
				text="Dashboard"
				:is-sidebar-open="isSidebarOpen"
				@toggle-sidebar="$emit('toggleSidebar')">
				<v-icon name="hi-home" scale="1.5" />
			</NavLink>

			<NavLink
				to="/tickets"
				text="Tickets"
				:is-sidebar-open="isSidebarOpen"
				@toggle-sidebar="$emit('toggleSidebar')">
				<v-icon name="hi-ticket" scale="1.5" />
			</NavLink>
		</nav>
	</div>
</template>

<script setup>
import NavLink from "./NavLink.vue";

defineProps({
	isSidebarOpen: {
		type: Boolean,
		default: false,
	},
});

defineEmits(["toggleSidebar"]);
</script>
